Create Project within OpenShift
redhat-cop/project-initialize-operator pull request #2
Opened 2020-02-27 22:55 UTC by cnuland

Use the project client within OpenShift to create a new Project based on the definition of the CR file

2020-02-28 13:24 UTC, gnekic commented
Looks solid to me! @cnuland Have you updated trello based on the TODO's that you left?

2020-02-28 22:25 UTC, sabre1041 requested changes
@cnuland A few comments inline but some additional comments

1. Please remove the binary artifact in `build/bin` directory
2. For some of the packages, do we want to adopt the following structure as it allows for different types of implementations?
       1. ldap -> identity
       2. git -> scm

Also be sure to keep in mind some of the patterns and thoughts in [onboarding-manager](https://github.com/redhat-cop/onboarding-manager)

2020-02-28 22:25 UTC, sabre1041 commented on README.md
> +$ oc sa get-token project-initialize
Save the output into a variable. Such as 

```
TOKEN=$(oc sa get-token project-initialize)
oc login --token="${TOKEN}"
```

2020-02-28 22:25 UTC, sabre1041 commented on README.md
> +$ operator-sdk up local --namespace="project-operator"
Latest `operator-sdk` uses the following command

```
operator-sdk run --local --namespace="project-operator"
```

2020-03-04 18:37 UTC, cnuland commented on README.md
> +$ operator-sdk up local --namespace="project-operator"
done

2020-03-04 18:37 UTC, cnuland commented on README.md
> +$ oc sa get-token project-initialize
done

2020-03-06 02:27 UTC, sabre1041 approved these changes
LGTM

2020-03-06 02:27 UTC, merged